---
title: "Publications"
bibliography: publications.json
suppress-bibliography: true
csl: "https://raw.githubusercontent.com/citation-style-language/styles/master/apa-cv.csl"
format: gfm
---

## Journal Articles
@imei.validation

@meier.ai.melody.continuation

@schaeferAnstrengungsbereitschaftBeimSingen2024

@schreiberCreativePerformanceAI2024

@HALTpart2

@kiyanPredictingImmersionSurround2023

@sanderLimitedEmotionalValue2023

@HALTpart1

@imei

## Conference Contributions
@sanderSehenStattHoeren2024

@meierMelodiefortsetzungMitKI2024

@sanderSightSoundJudgements2024

@kopiezMenschOderMaschine2024

@sanderKeineAuswirkungenMusikabstinenz2024

@rohrsKeineAuswirkungenMusikabstinenz2023

@schreiberKomponierenMitKunstlicher2023

@kopiezEffectsAudioFormat2023

@kopiezMeasurementImmersiveMusic2023

@sanderMessungImmersivenMusikErlebens2023

@wyciskAudioExperimenteImInternet2023

@kiyanRelationshipPerceivedImmersion2023

@hahn_reanalysis_dgm2022

@wagner3.0DGM2022

@HALTpresentation2022

@wyciskMessungImmersivenMusikErlebens2022

@IAQItmt2021

@HALTdgm2021

@IAQIdgm2021

@psychTestRpresentation2021

@HALT1presentation2021

@HALT2presentation2021

@longgoldDGM2020

## Misc
@HALTConfig

@HALTpackage

@icmpc16escom11tagunsbericht

@EGQpackage

@psyquest_introduction

