---
title: "Publications"
format:
  html:
    other-links:
    - text: "Download Zotero-json file"
      href: "https://raw.githubusercontent.com/KilianSander/publication-list/main/publications.json"
      icon: download
---

## Journal Articles

Schäfer, N., Kopiez, R., & Sander, K. (2024). Anstrengungsbereitschaft
beim Singen im Musikunterricht: Eine empirische Untersuchung möglicher
Einflussfaktoren. *Jahrbuch Musikpsychologie*, Article e197.
<https://doi.org/10.5964/jbdgm.197>

Schreiber, A., Sander, K., Kopiez, R., & Thöne, R. (2024). The creative
performance of the AI agents ChatGPT and Google Magenta compared to
human-based solutions in a standardized melody continuation task.
*Jahrbuch Musikpsychologie*, *32*, Article e195.
<https://doi.org/10.5964/jbdgm.195>

Wycisk, Y., Sander, K., Manca, B., Kopiez, R., & Platz, F. (2024). The
Headphone and Loudspeaker Test – Part II: A comprehensive playback
device screening method in Internet experiments. *Behavior Research
Methods*, *56*, 362–378. <https://doi.org/10.3758/s13428-022-02048-3>

Kiyan, R., Bergner, J., Preihs, S., Wycisk, Y., Schössow, D., Sander,
K., Peissig, J., & Kopiez, R. (2023). Towards predicting immersion in
surround sound music reproduction from sound field features. *Acta
Acustica*, *7*, Article 45. <https://doi.org/10.1051/aacus/2023040>

Sander, K., Wycisk, Y., & Kopiez, R. (2023). Limited emotional value
added by immersive 3D audio: A reanalysis. *Music & Science*, *6*.
<https://doi.org/10.1177/20592043231194751>

Wycisk, Y., Kopiez, R., Bergner, J., Sander, K., Preihs, S., Peissig,
J., & Platz, F. (2023). The Headphone and Loudspeaker Test – Part I:
Suggestions for controlling characteristics of playback devices in
internet experiments. *Behavior Research Methods*, *55*, 1094–1107.
<https://doi.org/10.3758/s13428-022-01859-8>

Wycisk, Y., Sander, K., Kopiez, R., Platz, F., Preihs, S., & Peissig, J.
(2022). Wrapped into sound: Development of the Immersive Music
Experience Inventory (IMEI). *Frontiers in Psychology*, *13*, 951161.
<https://doi.org/10.3389/fpsyg.2022.951161>

## Conference Contributions

Sander, K., Gutzmann, G., & Kopiez, R. (2024, September 6–8). *Sehen
statt Hören beim Bewerten von Musikdarbietungen? Konzeptionelle
Replikation der Hypothese der visuellen Dominanz von Tsay (2013)*
\[Poster presentation\]. 40. Jahrestagung der Deutschen Gesellschaft für
Musikpsychologie, München.

Meier, N., Schreiber, A., Sander, K., Kopiez, R., & Thöne (2024,
September 6–8). *Melodiefortsetzung mit KI: Die kreativen Leistungen
verschiedener Sprachmodelle im Vergleich zu Musikstudierenden* \[Poster
presentation\]. 40. Jahrestagung der Deutschen Gesellschaft für
Musikpsychologie, München.

Sander, K., Gutzmann, G., & Kopiez, R. (2024, July 3–6). *Sight over
sound in judgements of audio-visual music performances? Evidence from a
conceptual replication of Tsay’s (2013) visual dominance hypothesis*
\[Presentation\]. 12th Triennial Conference of the European Society for
the Cognitive Sciences of Music, York, UK.

Kopiez, R., Sander, K., Schulz, F., & Düvel, N. (2024, February 29–March
1). *„Mensch oder Maschine?“ – Ein Experiment zur Wahrnehmung
kompositorischer (Ko-)Kreativität Künstlicher Intelligenz*. Treffen der
Fachgruppe Systematische Musikwissenschaft in der Gesellschaft für
Musikforschung, Staatliches Institut für Musikforschung PK Berlin.

Sander, K., Röhrs, D., & Kopiez, R. (2024, February 23–24). *Keine
Auswirkungen der Musikabstinenz auf die Gesundheit: Eine Replikation der
Studie von Starcke et al. (2022)* \[Poster presentation\]. 22. Smposium
der Deutschen Gesellschaft für Musikphysiologie und Musikermedizin,
Hannover, Germany.

Röhrs, D., Sander, K., & Kopiez, R. (2023, September 8–10). *Keine
Auswirkungen der Musikabstinenz auf die Gesundheit: Eine Replikation der
Studie von Starcke et al. (2022)* \[Poster presentation\]. 39.
Jahrestagung der Deutschen Gesellschaft für Musikpsychologie, Hannover,
Germany.

Schreiber, A., Sander, K., & Kopiez, R. (2023, September 8–10).
*Komponieren mit künstlicher Intelligenz: Melodievervollständigungen von
Musikstudierenden der HMTMH im Vergleich mit den KIs* ChatGPT *und*
Google Magenta \[Poster presentation\]. 39. Jahrestagung der Deutschen
Gesellschaft für Musikpsychologie, Hannover, Germany.

Kopiez, R., Sander, K., Wycisk, Y., Platz, F., & Silas, S. (2023, June
15–16). *Effects of audio format, musical content, and their interaction
on the immersive music experience* \[Spatial audio presentation\].
Everyday is Spatial, Gloucestershire, UK.

Kopiez, R., Sander, K., Wycisk, Y., Platz, F., & Silas, S. (2023, June
15–16). *The measurement of immersive music experience: Development and
application of the Immersive Music Experience Inventory (IMEI)*
\[Presentation\]. Everyday is Spatial, Gloucestershire, UK.

Sander, K., Wycisk, Y., Kopiez, R., Platz, F., Peissig, J., Preihs, S.,
Kiyan, R., & Schössow, D. (2023, March 6–9). *Die Messung immersiven
Musik-Erlebens: Das Immersive Music Experience Inventory (IMEI)*
\[Presentation\]. DAGA: 49. Jahrestagung für Akustik, Hamburg, Germany.

Wycisk, Y., Sander, K., Manca, B., Kopiez, R., Bergner, J., Platz, F.,
Preihs, S., & Peissig, J. (2023, March 6–9). *Audio-Experimente im
Internet: Kontrolle über die Abhörbedingungen mittels des Headphone and
Loudspeaker Tests (HALT)* \[Presentation\]. DAGA: 49. Jahrestagung für
Akustik, Hamburg, Germany.

Kiyan, R., Bergner, J., Preihs, S., Schössow, D., Wycisk, Y., Sander,
K., Kopiez, R., Peissig, J., & Platz, F. (2023, March 6–9). *On the
relationship of perceived immersion to acoustic properties of surround
sound music reproduction* \[Presentation\]. DAGA: 49. Jahrestagung für
Akustik, Hamburg, Germany.

Sander, K., Wycisk, Y., & Kopiez, R. (2022, September 2–4). *Emotionaler
Mehrwert durch 3D-Audio? Vergleichende Reanalyse eines Datensatzes zum
Musik-Erleben in den Formaten Stereo, Surround und Auro-3D* \[Poster
presentation\]. 38. Jahrestagung der Deutschen Gesellschaft für
Musikpsychologie “Die Psychologie der populären Musik,” Würzburg,
Germany.

Kopiez, R., Wycisk, Y., Sander, K., Silas, S., Kiyan, R., Platz, F.,
Bergner, J., Schössow, D., Preihs, S., & Peissig, J. (2022, September
2–4). Immersives Musik-Erleben: Psychophysiologische Korrelate. In C.
Bullerjahn, *Immersives Musik-Erleben, Musik und Gaming* \[Conference
session\]. 38. Jahrestagung der Deutschen Gesellschaft für
Musikpsychologie “Die Psychologie der populären Musik,” Würzburg,
Germany.

Wycisk, Y., & Sander, K. (2022, July 28–30). The Headphone and
Loudspeaker Test. In R. Hake, *Special: Online hearing experiments*
\[Conference session\]. Hearing4all: Joint Research Academy 10th Annual
Summer School, Visselhövede, Germany.

Wycisk, Y., Sander, K., Kopiez, R., Platz, F., Peissig, J., & Preihs, S.
(2022, March 21–24). *Messung immersiven Musik-Erlebens: Das Immersive
Audio Quality Inventory* \[Poster presentation\]. DAGA 2022: 48.
Jahrestagung für Akustik, Stuttgart, Germany.

Kopiez, R., Sander, K., Wycisk, Y., Platz, F., Bergner, J., Preihs, S.,
& Peissig, J. (2021, November 3–6). *The measurement of 3D-audio
experience: The „Immersive Audio Quality Inventory"* \[Presentation\].
31. Tonmeistertagung, Düsseldorf, Germany.

Wycisk, Y., Kopiez, R., Sander, K., Manca, B., Bergner, J., Preihs, S.,
Peissig, J., & Platz, F. (2021, September 2–3). *Der Headphone and
Loudspeaker Test (HALT): Vorschläge für die kontrollierte Verwendung von
Wiedergabegeräten in Internet-Experimenten* \[Poster presentation\]. 37.
Jahrestagung der Deutschen Gesellschaft für Musikpsychologie “Musik und
soziale Verbundenheit,” Virtuelle Posterkonferenz.

Sander, K., Wycisk, Y., Kopiez, R., Platz, F., Bergner, J., Peissig, J.,
& Preihs, S. (2021, September 2–3). *Messung immersiven Musik-Erlebens:
Das Immersive Audio Quality Inventory* \[Poster presentation\]. 37.
Jahrestagung der Deutschen Gesellschaft für Musikpsychologie “Musik und
soziale Verbundenheit,” Virtuelle Konferenz.

Harrison, P. M. C., Pausch, V., Sander, K., Höger, F., Frieler, K., &
Müllensiefen, D. (2021, July 28–31). *psychTestR: A platform for
individual differences research in music psychology* \[Presentation\].
16th International Conference on Music Perception and Cognition/11th
Conference of the European Society for the Cognitive Sciences of Music,
Fully virtual conferencing.

Wycisk, Y., Kopiez, R., Sander, K., Bergner, J., Preihs, S., Peissig,
J., & Platz, F. (2021, July 28–31). *Bringing confounding variables to a
HALT: Suggestions for the controlled use of playback devices in internet
experiments* \[Presentation\]. 16th International Conference on Music
Perception and Cognition/11th Conference of the European Society for the
Cognitive Sciences of Music, Fully virtual conferencing.

Sander, K., Wycisk, Y., Kopiez, R., Manca, B., & Platz, F. (2021, July
28–31). *Headphone and loudspeaker screening for web-based auditory
experiments: Suggestions for a reliable estimation of data quality and
sample size* \[Poster presentation\]. 16th International Conference on
Music Perception and Cognition/11th Conference of the European Society
for the Cognitive Sciences of Music, Fully virtual conferencing.

Sander, K., Pausch, V., Frieler, K., Müllensiefen, D., & Höger, F.
(2020, September 3–6). *Empirische Normwerte von Jugendlichen für
psychosoziale Fragebogeninstrumente aus dem R-Paket psyquest mit
Bedeutung für die musikalische Entwicklungsforschung* \[Poster
presentation\]. 36. Jahrestagung der Deutschen Gesellschaft für
Musikpsychologie, Virtuelle Posterkonferenz.

## Misc

Frieler, K., Wycisk, Y., & Sander, K. (2023). *HALTConfig* (Version 1.2)
\[Shiny app\]. <https://github.com/KilianSander/HALTConfig>

Frieler, K., Wycisk, Y., & Sander, K. (2022). *HALT* (Version 0.12.2)
\[R package\]. <https://github.com/KilianSander/HALT>

Sander, K., & Wycisk, Y. (2022). ICMPC16/ESCOM11, 28.-31. Juli 2021,
Fully virtual Conferencing \[Tagungsbericht\]. *Jahrbuch
Musikpsychologie*, *30*, 239–241.

Sander, K., & Labonde, P. (2021). *groovescale* (Version 0.9.0) \[R
package\]. <https://github.com/KilianSander/groovescale>

Sander, K., Pausch, V., Müllensiefen, D., Höger, F., & Frieler, K.
(2020). *Introduction to psyquest -- Deploying psychosocial and
music-related questionnaires for data collection in R*.
<http://media.gold-msi.org/misc/psyquest_introduction_v17.pdf>


```{r time}
#| echo: false
current_time <- Sys.time() |> strftime(format = "%Y-%m-%d %H:%M:%S %Z")
```
This page was last updated on `r current_time`.
